/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-highest': '#e3e2df',
        'score-none-bg': '#F4F3EF',
        'score-high-bg': '#F0FDF4',
        'border-default': '#E4E4E0',
        'score-mid-text': '#1547C0',
        'surface-container-low': '#f5f4f0',
        'accent-light': '#EEF2FF',
        'surface-container-high': '#e9e8e4',
        'secondary-container': '#e2dfdd',
        'on-surface': '#1b1c1a',
        'text-muted': '#A3A3A0',
        'text-secondary': '#6B6B68',
        'surface-variant': '#e3e2df',
        'surface-elevated': '#F9F9F7',
        'surface-container': '#efeeea',
        'score-low-bg': '#FFFBEB',
        'surface-card': '#FFFFFF',
        'primary': '#003fb1',
        'text-primary': '#0D0D0C',
        'primary-fixed': '#dbe1ff',
        'score-mid-bg': '#EEF2FF',
        'error': '#ba1a1a',
        'on-background': '#1b1c1a',
        'accent-hover': '#1347C5',
        'surface-dim': '#dbdad6',
        'primary-container': '#1a56db',
        'background': '#faf9f5',
        'score-low-text': '#92400E',
        'on-surface-variant': '#434654',
        'inverse-primary': '#b5c4ff',
        'on-primary': '#ffffff',
        'on-primary-container': '#d4dcff',
        'inverse-surface': '#30312e',
        'inverse-on-surface': '#f2f1ed',
        'page-bg': '#F4F3EF',
        'surface': '#faf9f5',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'score-none-text': '#6B6B68',
        'border-strong': '#C9C9C4',
        'on-primary-fixed': '#00174d',
        'surface-container-lowest': '#ffffff',
        'score-high-text': '#166534',
        'surface-tint': '#1353d8',
        'outline': '#737686',
        'outline-variant': '#c3c5d7',
        'secondary': '#5f5e5d',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#646261',
        'tertiary': '#852b00',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#ad3b00',
      },
      fontFamily: {
        'sans': ['Inter', 'sans-serif'],
        'mono': ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-base': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'button-text': ['13px', { lineHeight: '16px', fontWeight: '500' }],
        'data-label': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
        'data-value': ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
      spacing: {
        'nav-height': '52px',
        'row-height': '52px',
        'input-height': '36px',
        'margin-page': '24px',
        'gutter': '16px',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
      },
    },
  },
  plugins: [],
}
